/**
 * Картинки предметов (патч 76) — СГЕНЕРИРОВАНО, править руками нечего:
 * `python tools/icon_assets.py`.
 *
 * Ключ — id предмета в игре, тот же, что в контенте и в БД. Поэтому
 * подпись искать не нужно: есть ore_id — есть иконка.
 */

const ICONS = {
  'base:armor:Кираса': new URL('./assets/items/base_armor_kirasa.webp', import.meta.url).href,
  'base:armor:Панцирь': new URL('./assets/items/base_armor_pancir.webp', import.meta.url).href,
  'base:armor:Роба': new URL('./assets/items/base_armor_roba.webp', import.meta.url).href,
  'base:boots:Ботфорты': new URL('./assets/items/base_boots_botforty.webp', import.meta.url).href,
  'base:boots:Поршни': new URL('./assets/items/base_boots_porshni.webp', import.meta.url).href,
  'base:boots:Сапоги': new URL('./assets/items/base_boots_sapogi.webp', import.meta.url).href,
  'base:helmet:Венец': new URL('./assets/items/base_helmet_venec.webp', import.meta.url).href,
  'base:helmet:Капюшон': new URL('./assets/items/base_helmet_kapyushon.webp', import.meta.url).href,
  'base:helmet:Шлем': new URL('./assets/items/base_helmet_shlem.webp', import.meta.url).href,
  'base:legs:Набедренники': new URL('./assets/items/base_legs_nabedrenniki.webp', import.meta.url).href,
  'base:legs:Поножи': new URL('./assets/items/base_legs_ponozhi.webp', import.meta.url).href,
  'base:legs:Штаны': new URL('./assets/items/base_legs_shtany.webp', import.meta.url).href,
  'base:weapon:Кинжал': new URL('./assets/items/base_weapon_kinzhal.webp', import.meta.url).href,
  'base:weapon:Клинок': new URL('./assets/items/base_weapon_klinok.webp', import.meta.url).href,
  'base:weapon:Посох': new URL('./assets/items/base_weapon_posoh.webp', import.meta.url).href,
  'base:weapon:Секира': new URL('./assets/items/base_weapon_sekira.webp', import.meta.url).href,
  'base:weapon:Тесак': new URL('./assets/items/base_weapon_tesak.webp', import.meta.url).href,
  'chest:crimson': new URL('./assets/items/chest_crimson.webp', import.meta.url).href,
  'chest:dim': new URL('./assets/items/chest_dim.webp', import.meta.url).href,
  'chest:dusty': new URL('./assets/items/chest_dusty.webp', import.meta.url).href,
  'chest:searing': new URL('./assets/items/chest_searing.webp', import.meta.url).href,
  'chest:tear': new URL('./assets/items/chest_tear.webp', import.meta.url).href,
  'craft:dps': new URL('./assets/items/craft_dps.webp', import.meta.url).href,
  'craft:support': new URL('./assets/items/craft_support.webp', import.meta.url).href,
  'craft:tank': new URL('./assets/items/craft_tank.webp', import.meta.url).href,
  'elixir:ashen_fever': new URL('./assets/items/elixir_ashen_fever.webp', import.meta.url).href,
  'elixir:ashen_haze': new URL('./assets/items/elixir_ashen_haze.webp', import.meta.url).href,
  'elixir:blood_clarity': new URL('./assets/items/elixir_blood_clarity.webp', import.meta.url).href,
  'elixir:blood_for_blood': new URL('./assets/items/elixir_blood_for_blood.webp', import.meta.url).href,
  'elixir:heal_large': new URL('./assets/items/elixir_heal_large.webp', import.meta.url).href,
  'elixir:heal_medium': new URL('./assets/items/elixir_heal_medium.webp', import.meta.url).href,
  'elixir:heal_small': new URL('./assets/items/elixir_heal_small.webp', import.meta.url).href,
  'elixir:last_breath': new URL('./assets/items/elixir_last_breath.webp', import.meta.url).href,
  'elixir:second_heart': new URL('./assets/items/elixir_second_heart.webp', import.meta.url).href,
  'elixir:shard_blood': new URL('./assets/items/elixir_shard_blood.webp', import.meta.url).href,
  'fish:ashen_roach': new URL('./assets/items/fish_ashen_roach.webp', import.meta.url).href,
  'fish:ashen_sturgeon': new URL('./assets/items/fish_ashen_sturgeon.webp', import.meta.url).href,
  'fish:black_catfish': new URL('./assets/items/fish_black_catfish.webp', import.meta.url).href,
  'fish:blind_gudgeon': new URL('./assets/items/fish_blind_gudgeon.webp', import.meta.url).href,
  'fish:bone_pike': new URL('./assets/items/fish_bone_pike.webp', import.meta.url).href,
  'fish:brackish_bream': new URL('./assets/items/fish_brackish_bream.webp', import.meta.url).href,
  'fish:crimson_burbot': new URL('./assets/items/fish_crimson_burbot.webp', import.meta.url).href,
  'fish:deep_tear': new URL('./assets/items/fish_deep_tear.webp', import.meta.url).href,
  'fish:drowned_flounder': new URL('./assets/items/fish_drowned_flounder.webp', import.meta.url).href,
  'fish:marked_carp': new URL('./assets/items/fish_marked_carp.webp', import.meta.url).href,
  'fish:monolith_catfish': new URL('./assets/items/fish_monolith_catfish.webp', import.meta.url).href,
  'fish:pale_perch': new URL('./assets/items/fish_pale_perch.webp', import.meta.url).href,
  'fish:reed_spinefish': new URL('./assets/items/fish_reed_spinefish.webp', import.meta.url).href,
  'fish:rusty_tench': new URL('./assets/items/fish_rusty_tench.webp', import.meta.url).href,
  'fish:sewer_lamprey': new URL('./assets/items/fish_sewer_lamprey.webp', import.meta.url).href,
  'fish:taint_eel': new URL('./assets/items/fish_taint_eel.webp', import.meta.url).href,
  'fish:the_nameless': new URL('./assets/items/fish_the_nameless.webp', import.meta.url).href,
  'fish:whisper_chub': new URL('./assets/items/fish_whisper_chub.webp', import.meta.url).href,
  'misc:raid_key': new URL('./assets/items/misc_raid_key.webp', import.meta.url).href,
  'mount:admin_ashen_herald': new URL('./assets/items/mount_admin_ashen_herald.webp', import.meta.url).href,
  'mount:ashen_steed': new URL('./assets/items/mount_ashen_steed.webp', import.meta.url).href,
  'ore:ashen_silver': new URL('./assets/items/ore_ashen_silver.webp', import.meta.url).href,
  'ore:brown_iron': new URL('./assets/items/ore_brown_iron.webp', import.meta.url).href,
  'ore:crimson_cluster': new URL('./assets/items/ore_crimson_cluster.webp', import.meta.url).href,
  'ore:living_stone': new URL('./assets/items/ore_living_stone.webp', import.meta.url).href,
  'ore:salt_quartz': new URL('./assets/items/ore_salt_quartz.webp', import.meta.url).href,
  'ore:taint_pyrite': new URL('./assets/items/ore_taint_pyrite.webp', import.meta.url).href,
  'rarity:admin': new URL('./assets/items/rarity_admin.webp', import.meta.url).href,
  'rarity:common': new URL('./assets/items/rarity_common.webp', import.meta.url).href,
  'rarity:epic': new URL('./assets/items/rarity_epic.webp', import.meta.url).href,
  'rarity:legendary': new URL('./assets/items/rarity_legendary.webp', import.meta.url).href,
  'rarity:rare': new URL('./assets/items/rarity_rare.webp', import.meta.url).href,
  'rarity:uncommon': new URL('./assets/items/rarity_uncommon.webp', import.meta.url).href,
  'rarity:unique': new URL('./assets/items/rarity_unique.webp', import.meta.url).href,
  'subclass:blood_knight': new URL('./assets/items/subclass_blood_knight.webp', import.meta.url).href,
  'subclass:dark_mystic': new URL('./assets/items/subclass_dark_mystic.webp', import.meta.url).href,
  'subclass:elementalist': new URL('./assets/items/subclass_elementalist.webp', import.meta.url).href,
  'subclass:guardian': new URL('./assets/items/subclass_guardian.webp', import.meta.url).href,
  'subclass:poisoner': new URL('./assets/items/subclass_poisoner.webp', import.meta.url).href,
  'subclass:shadow_blade': new URL('./assets/items/subclass_shadow_blade.webp', import.meta.url).href,
  'tool:100': new URL('./assets/items/tool_100.webp', import.meta.url).href,
  'tool:110': new URL('./assets/items/tool_110.webp', import.meta.url).href,
  'tool:120': new URL('./assets/items/tool_120.webp', import.meta.url).href,
  'tool:90': new URL('./assets/items/tool_90.webp', import.meta.url).href,
  'trophy:ash_dust': new URL('./assets/items/trophy_ash_dust.webp', import.meta.url).href,
  'trophy:blood_shard': new URL('./assets/items/trophy_blood_shard.webp', import.meta.url).href,
  'trophy:heart_spike': new URL('./assets/items/trophy_heart_spike.webp', import.meta.url).href,
  'trophy:monolith_tear': new URL('./assets/items/trophy_monolith_tear.webp', import.meta.url).href,
  'trophy:taint_clot': new URL('./assets/items/trophy_taint_clot.webp', import.meta.url).href,
  'unique:surgeon_scalpel': new URL('./assets/items/unique_surgeon_scalpel.webp', import.meta.url).href,
};

/** Картинка предмета или null — вызывающий сам решает, чем заменить. */
export function itemIcon(key) {
  return ICONS[key] ?? null;
}
